DROP TABLE IF EXISTS uc_rel CASCADE;
CREATE TABLE uc_rel (
    ucr_ID SERIAL PRIMARY KEY NOT NULL,
    uID INT,
    cID INT,
    goal NUMERIC,
    FOREIGN KEY (aID) REFERENCES challenge (cID),
    FOREIGN KEY (uId) REFERENCES users (uId)
);
